# 2. Handle all the 5 different Erros using Exception Handling.

# index error
# l1 = [1, 2, 3]
# try:
#     print(l1[3])
# except:
#     print("out of range index")

#  key error
# d1={}
# try:
#     print(d1["3"])
# except:
#     print("key error")



# Type error

# strg="inamhusain"
# try:
#     print(strg+55)
# except:
#     print("'str' and 'int' not concatenate")


# Name error
# x=10
# try:
#     def my():
#         print(y)
#     my()
# except:
#     print("y is not found")



# value error
# i=[1,2,4,8,6]
#
# try:
#     print(i.remove(3))
#
# except:
#     print("value not in list")
